version: '3'
services:
  api:
    container_name: 'nodejs2023q2-api'
    image: vladtarnovskiy/api
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - appnet
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    restart: always
    env_file:
      - .env
  postgres:
    container_name: 'nodejs2023q2-postgres-db'
    image: vladtarnovskiy/postgres-db
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - appnet
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PG_HOST=${PG_HOST}
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./logs:/logs

networks:
  appnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgres:
  logs:
